import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Desktop Project",
  description: "Generated by create next app",
};

interface ChildrenProps {
  children: React.ReactNode;
}

export default function MainLayout({ children }: ChildrenProps) {
  return (<>
  {children}
  </>);
}
